#pragma once

//! \file zc_speaker.h
//! \brief Audio output using PortAudio

// PortAudio
#include "portaudio.h"

#include "zc_audio_data.h"

#include <atomic>
#include <functional>
#include <queue>
#include <string>
#include <thread>
#include <vector>

//! Minimum speech volume (dB relative to full-scale) 
//! data is made zero at this value.
constexpr float MINIMUM_VOLUME = -40.0F;

//! \brief The class forwards the audio data generated by the synthesiser
//! to the audio driver using PortAudio.
class zc_speaker {

public:
    //! \brief Constructor.
    //! \param speech synthesised audio data queue
    zc_speaker(std::queue<zc_audio_data>* speech);

    //! Destructor
    ~zc_speaker();

    //! \brief Enable audio out.
    //! \return true if successfully enabled.
    bool enable();

    //! \brief Reset back to disconnected, but connectable state.
    //! \return true if successful
    bool reset();

    //! Returns true if audio out is initialised.
    bool ready() const;

    //! Returns true of audio out is enabled.
    bool enabled() const;

    //! Returns true if audio not being output.
    bool idle() const;

    //! Set the port 
    //! \param port_number local index of the port to be used.
    bool use_port(int port_number);

    //! Get the available ports that support \param sample_rate
    std::vector<std::string> get_ports(float sample_rate);

    //! Set buffer depth
    void buffer_depth(int d);
    //! Get buffer depth
    int buffer_depth() const;
    //! Set volume
    void volume(float v);
    //! Get volume
    float volume() const;

    //! Get port list index
    int port_number() const;

    //! Set callback for audio output monitoring
    //! \param callback function to be called with each audio sample
    void set_audio_callback(std::function<void(float)> callback);

    //! Set callback for metadata output
    //! \param callback function to be called with text metadata
    void set_text_callback(std::function<void(const std::string&)> callback);

	//! \brief Callback from PortAudio.
	//! \param input buffer containing received audio data - not used.
	//! \param output buffer to receive audio data
	//! \param frameCount Number of samples per buffer
	//! \param timeInfo Timing information
	//! \param statusFlags Stream callback flags
	//! \param userData pointer to the zc_speaker instance
	static int cb_pa_stream(const void* input,
		void* output,
		unsigned long frameCount,
		const PaStreamCallbackTimeInfo* timeInfo,
		PaStreamCallbackFlags statusFlags,
		void* userData);



protected:
	//! Load the settings 
	void load_settings();

	//! Save the settings
	void save_settings();

	//! \brief instance specific version of callback
	//! \param input Unused input buffer
	//! \param output buffer to receive audio data
	//! \param frameCount Number of frames per buffer
	//! \param timeInfo Timing information
	//! \param statusFlags Stream callback flags
	int pa_stream(const void* input,
		void* output,
		unsigned long frameCount,
		const PaStreamCallbackTimeInfo* timeInfo,
		PaStreamCallbackFlags statusFlags);

    //! \brief Initialise specific port
    bool initialise_port();
    
    //! \brief Close down portaudio
    bool close_pa();

    //! \brief Disconnect current port
    bool disconnect_port();

    //! \brief Convert volume control value (-20dB to 0) to multiplier
    float v2x(float v);

    //! Speech audio stream
    std::queue<zc_audio_data>* speech_ = nullptr;

    //! Audio output stream
    PaStream* stream_ = nullptr;

    //! Stream parameters
    PaStreamParameters parameters_;

    //! \todo add audio port configuration data
    
    //! Sample rate (samples per second)
    float sample_rate_ = 0.0F;

    //! Depth of buffer
    int buffer_depth_ = 0;

    //! Volume (between -20 dB and 0 dB)
    float volume_ = 0.0F;

    //! Volume multiplier (= 10^(V/10))
    float vol_xier_ = 1.0F;

    //! Audio port index
    PaDeviceIndex port_index_;

    //! Local port index
    size_t port_number_;

    //! Audio port name
    std::string port_name_;

    //! Current buffers
    zc_audio_data* next_buffer_ = nullptr;

    //! Number of accesses to current buffer
    unsigned long samples_sent_ = 0UL;

    //! Idle
    bool idle_ = false;

    //! The audio is in operational state.
    bool enabled_ = false;

    //! Portaudio initialised
    bool pa_initialised_ = false;

    //! Portaudio has been initialised and appears to support the required audio.
    //! If neither \a enabled_ nor \a ready_ are true, the audio is in transition between
    //! the two valid states, yet to be initialised, or does not support the
    //! required sample rate.
    bool ready_ = false;

    //! List of port indices, itself indexed locally
    std::vector<PaDeviceIndex> port_indices_ = {};
    //! List of port names, indexed by the samae
    std::vector<std::string> port_names_ = {};
    //! List of port names prefixed with index.
    std::vector<std::string> annotated_names_ = {};

    //! Callback for audio output monitoring
    std::function<void(float)> audio_callback_ = nullptr;

    //! Callback for metadata output
    std::function<void(const std::string&)> text_callback_ = nullptr;

};
